domis/curriculum/urls.py
from django.urls import path
from . import views
app_name = 'curriculum'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpDateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(), name='lesson_delete')
  
]

domis/domis/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import ronin
  
  
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ronin.urls')),
    path('curriculum/', include('curriculum.urls'))
]
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

domis/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <div class="jumbotron">
            <a href="{% url 'index' %}">Home</a>
          
            <a href="{% url 'register' %}">Register</a>
            {% if user.is_authenticated %}
            <a href="{% url 'user_logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'user_login' %}">Login</a>
            {% endif %}
            <a href="{% url 'admin:index'%}">admin</a>
            <a href="{% url 'curriculum:standard_list'%}">standards</a>
            <h2>Welcome..To get started Just Register</h2>
            {% block content %}

            {% endblock %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>